name: Check radar Service
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'radar-service/**/*'  # path for the service folder Whenever you will make changes in this folder. Checks will trigger 
  push:
    branches:
      - develop
    paths:
      - 'radar-service/**/*' # path for the service folder Whenever you will make changes in this folder. Checks will trigger 


env:
  ORG: knoldus Inc
  PROJECT_NAME: knoldus-leaderboard
  AUTHOR: MuZakkir Saifi(muzakkirsaifi123)


jobs:
  build:
    name: Checks for radar-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

          
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        working-directory: radar-service/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_RADAR }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        run: |
          ./gradlew clean
          ./gradlew test
          ./gradlew jacocoTestReport
          ./gradlew sonar --info -Dsonar.projectKey=${{ secrets.PROJECT_KEY_RADAR }}